# Generated by Django 2.0.1 on 2018-01-24 13:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import studentmgr.models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgr', '0002_auto_20180122_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeType', models.IntegerField(choices=[(0, '报名交费'), (1, '其他杂费'), (2, '挂靠结算')], default=0, verbose_name='交费类别')),
                ('note', models.CharField(max_length=100, verbose_name='备注')),
                ('money', models.IntegerField(default=0, verbose_name='收费金额')),
                ('feeId', models.CharField(default=studentmgr.models.increment_fee_id, editable=False, max_length=15, verbose_name='编号')),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登记时间')),
            ],
            options={
                'verbose_name': '费用',
                'verbose_name_plural': '费用',
            },
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': '渠道', 'verbose_name_plural': '渠道'},
        ),
        migrations.AlterModelOptions(
            name='classtype',
            options={'verbose_name': '班型', 'verbose_name_plural': '班型'},
        ),
        migrations.AlterModelOptions(
            name='enroller',
            options={'verbose_name': '招生代表', 'verbose_name_plural': '招生代表'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学员', 'verbose_name_plural': '学员'},
        ),
        migrations.AddField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmgr.Student', verbose_name='交费学员'),
        ),
    ]
