# Generated by Django 2.0.1 on 2018-01-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgr', '0003_auto_20180124_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
