# Generated by Django 2.0.1 on 2018-01-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgr', '0004_auto_20180124_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'verbose_name': '交费记录', 'verbose_name_plural': '交费记录'},
        ),
        migrations.AlterField(
            model_name='classtype',
            name='price',
            field=models.CharField(max_length=10, verbose_name='班型价格'),
        ),
    ]
