# Generated by Django 2.0.1 on 2018-01-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgr', '0005_auto_20180125_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='money',
            field=models.CharField(max_length=10, verbose_name='收费金额'),
        ),
    ]
