# Generated by Django 2.0.1 on 2018-01-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgr', '0006_auto_20180125_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='paymentMethod',
            field=models.IntegerField(choices=[(0, '现金支付'), (1, 'POS机刷卡'), (2, '微信转账(个人收款码)'), (3, '微信支付'), (4, '支付宝转账(个人收款码)'), (5, '支付宝付款')], default=0, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='feeType',
            field=models.IntegerField(choices=[(0, '培训费'), (1, '其他杂费'), (2, '挂靠结算')], default=0, verbose_name='交费类别'),
        ),
    ]
