# Generated by Django 2.0.1 on 2018-02-05 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgr', '0008_exam_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='手机号')),
                ('idNo', models.CharField(blank=True, max_length=20, null=True, verbose_name='证件号')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '教练',
                'verbose_name_plural': '教练',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(default=django.utils.timezone.now, verbose_name='审查日期')),
                ('startDate', models.DateField(default=django.utils.timezone.now, verbose_name='生效日期')),
                ('endDate', models.DateField(default=django.utils.timezone.now, verbose_name='失效日期')),
            ],
            options={
                'verbose_name': '年审',
                'verbose_name_plural': '年审',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fType', models.IntegerField(choices=[(0, '气'), (1, '油')], default=0, verbose_name='类型')),
                ('money', models.CharField(max_length=10, verbose_name='金额')),
                ('createDate', models.DateField(default=django.utils.timezone.now, verbose_name='加油时间')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmgr.Coach', verbose_name='上报教练')),
            ],
            options={
                'verbose_name': '油气',
                'verbose_name_plural': '油气',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20, verbose_name='保险公司')),
                ('insType', models.CharField(max_length=20, verbose_name='险种')),
                ('money', models.CharField(max_length=10, verbose_name='保险金额')),
                ('createDate', models.DateField(default=django.utils.timezone.now, verbose_name='投保时间')),
                ('startDate', models.DateField(default=django.utils.timezone.now, verbose_name='生效时间')),
                ('endDate', models.DateField(default=django.utils.timezone.now, verbose_name='失效时间')),
            ],
            options={
                'verbose_name': '保险',
                'verbose_name_plural': '保险',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.CharField(max_length=10, verbose_name='维修费用')),
                ('createDate', models.DateField(default=django.utils.timezone.now, verbose_name='维修时间')),
                ('note', models.TextField(blank=True, null=True, verbose_name='维修说明')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmgr.Coach', verbose_name='上报教练')),
            ],
            options={
                'verbose_name': '维修',
                'verbose_name_plural': '维修',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=15, verbose_name='车辆编号')),
                ('vin', models.CharField(max_length=20, verbose_name='车架号')),
                ('licId', models.CharField(max_length=10, verbose_name='车牌号')),
                ('licDate', models.DateField(default=django.utils.timezone.now, verbose_name='上牌日期')),
                ('use', models.IntegerField(choices=[(0, '驾校车辆'), (1, '考场车辆'), (2, '公务用车')], default=0, verbose_name='车辆用途')),
                ('name', models.CharField(max_length=20, verbose_name='车主姓名')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '车辆',
                'verbose_name_plural': '车辆',
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-id',), 'verbose_name': '学员', 'verbose_name_plural': '学员'},
        ),
        migrations.AlterField(
            model_name='student',
            name='addr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='住址'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='veh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmgr.Vehicle', verbose_name='车辆'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='veh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmgr.Vehicle', verbose_name='车辆'),
        ),
        migrations.AddField(
            model_name='fuel',
            name='veh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmgr.Vehicle', verbose_name='车辆'),
        ),
        migrations.AddField(
            model_name='examination',
            name='veh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmgr.Vehicle', verbose_name='车辆'),
        ),
    ]
