# Generated by Django 2.0.1 on 2018-02-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgr', '0010_vehicle_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pyFirstLetters',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='拼音首字母'),
        ),
        migrations.AddField(
            model_name='student',
            name='pyFull',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='全拼'),
        ),
    ]
