# Generated by Django 2.0.1 on 2018-02-22 02:32

from django.db import migrations
from pypinyin import lazy_pinyin, Style


def add_pinyin_fields(apps, schema_editor):
    students = apps.get_model('studentmgr', 'Student')
    for stu in students.objects.all():
        stu.pyFirstLetters = ''.join(lazy_pinyin(stu.name, style=Style.FIRST_LETTER, errors='ignore'))
        stu.pyFull = ''.join(lazy_pinyin(stu.name, errors='ignore'))
        stu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgr', '0011_auto_20180222_1016'),
    ]

    operations = [
        migrations.RunPython(add_pinyin_fields),
    ]
